package com.partner541.database.dao;

import com.partner541.database.model.KPI;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface KPIDao {
    String INSERT_FIELDS = " START_TIME, CYCLE, NE_NAME, SECTOR, SECTOR_NAME, RRC_CONNECT_COMPLETE_TIME, RRC_CONNECT_REQUEST_TIME, " +
            "RRC_SET_SUCC_RATE, ERAB_SET_SUCCESS_TIME, ERAB_TRY_CONNECT_TIME, ERAB_SET_SUCCESS_TWO, eNodeB_TRYGGER_EXCEP_RELE_TIME, " +
            "SECTOR_SWITCH_ERAB_EXCEP_RELE_TIME, ERAB_DROP_RATE, WIRELESS_CONN_RATE, eNodeB_INIT_S1, UE_Context_EXCEP_RELE_TIME, " +
            "UE_Context_SET_SUCCESS_TIME, WIRELESS_DROP_RATE, eNodeB_IN_DIFF_FREQ_SWITCH_SUCC_TIME, eNodeB_IN_DIFF_FREQ_SWITCH_TRY_TIME, " +
            "eNodeB_IN_SAME_FREQ_SWITCH_SUCC_TIME, eNodeB_IN_SAME_FREQ_SWITCH_TRY_TIME, eNodeB_BETWEEN_DIFF_FREQ_SWITCH_SUCC_TIME, " +
            "eNodeB_BETWEEN_DIFF_FREQ_SWITCH_TRY_TIME, eNodeB_BETWEEN_SAME_FREQ_SWITCH_SUCC_TIME, eNodeB_BETWEEN_SAME_FREQ_SWITCH_TRY_TIME, " +
            "eNB_IN_SWITCH_SUCC_RATE, eNB_BETWEEN_SWITCH_SUCC_RATE, SAME_FREQ_SWITCH_SUCC_ZSP, DIFF_FREQ_SWITCH_SUCC_ZSP, SWITCH_SUCC_RATE, " +
            "SECTOR_DPCP_RECV_UP_DATE_THROUGHPUT, SECTOR_DPCP_RECV_DOWN_DATE_THROUGHPUT, RPC_RESET_REQUEST_TIME, RPC_CONN_RESET_RATE, " +
            "TO_ONE, TO_TWO, TO_THREE, TO_FOUR, eNB_IN_SWITCH_SUCC_TIME, eNB_IN_SWITCH_REQUEST_TIME ";

    String VALUES_FIELDS = " #{STARTTIME}, #{CYCLE}, #{NENAME}, #{SECTOR}, #{SECTORNAME}, #{RRCCONNECTCOMPLETETIME}, #{RRCCONNECTREQUESTTIME}, " +
            "#{RRCSETSUCCRATE}, #{ERABSETSUCCESSTIME}, #{ERABTRYCONNECTTIME}, #{ERABSETSUCCESSTWO}, #{eNodeBTRYGGEREXCEPRELETIME}, " +
            "#{SECTORSWITCHERABEXCEPRELETIME}, #{ERABDROPRATE}, #{WIRELESSCONNRATE}, #{eNodeBINITS1}, #{UEContextEXCEPRELETIME}, " +
            "#{UEContextSETSUCCESSTIME}, #{WIRELESSDROPRATE}, #{eNodeBINDIFFFREQSWITCHSUCCTIME}, #{eNodeBINDIFFFREQSWITCHTRYTIME}, " +
            "#{eNodeBINSAMEFREQSWITCHSUCCTIME}, #{eNodeBINSAMEFREQSWITCHTRYTIME}, #{eNodeBBETWEENDIFFFREQSWITCHSUCCTIME}, " +
            "#{eNodeBBETWEENDIFFFREQSWITCHTRYTIME}, #{eNodeBBETWEENSAMEFREQSWITCHSUCCTIME}, #{eNodeBBETWEENSAMEFREQSWITCHTRYTIME}, " +
            "#{eNBINSWITCHSUCCRATE}, #{eNBBETWEENSWITCHSUCCRATE}, #{SAMEFREQSWITCHSUCCZSP}, #{DIFFFREQSWITCHSUCCZSP}, #{SWITCHSUCCRATE}, " +
            "#{SECTORDPCPRECVUPDATETHROUGHPUT}, #{SECTORDPCPRECVDOWNDATETHROUGHPUT}, #{RPCRESETREQUESTTIME}, #{RPCCONNRESETRATE}, " +
            "#{TOONE}, #{TOTWO}, #{TOTHREE}, #{TOFOUR}, #{eNBINSWITCHSUCCTIME}, #{eNBINSWITCHREQUESTTIME} ";
    @Insert({"insert into tbKPI (", INSERT_FIELDS, ") values( ", VALUES_FIELDS, " )"})
    int insertKPI(KPI kpi);

    @Delete({"delete from tbKPI"})
    int deleteKPI();
}
